/* Generated by wayland-scanner 1.18.0 */

#include <stdlib.h>
#include <stdint.h>
#include <gtk-shell.h>

extern const struct wl_interface gtk_surface1_interface;
extern const struct wl_interface wl_surface_interface;

static const struct wl_interface *gtk_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&gtk_surface1_interface,
	&wl_surface_interface,
	&gtk_surface1_interface,
};

static const struct wl_message gtk_shell1_requests[] = {
	{ "get_gtk_surface", "no", gtk_types + 6 },
	{ "set_startup_id", "?s", gtk_types + 0 },
	{ "system_bell", "?o", gtk_types + 8 },
	{ "notify_launch", "3s", gtk_types + 0 },
};

static const struct wl_message gtk_shell1_events[] = {
	{ "capabilities", "u", gtk_types + 0 },
};

const struct wl_interface gtk_shell1_interface = {
	"gtk_shell1", 3,
	4, gtk_shell1_requests,
	1, gtk_shell1_events,
};

static const struct wl_message gtk_surface1_requests[] = {
	{ "set_dbus_properties", "?s?s?s?s?s?s", gtk_types + 0 },
	{ "set_modal", "", gtk_types + 0 },
	{ "unset_modal", "", gtk_types + 0 },
	{ "present", "u", gtk_types + 0 },
	{ "request_focus", "3?s", gtk_types + 0 },
};

static const struct wl_message gtk_surface1_events[] = {
	{ "configure", "a", gtk_types + 0 },
	{ "configure_edges", "2a", gtk_types + 0 },
};

const struct wl_interface gtk_surface1_interface = {
	"gtk_surface1", 3,
	5, gtk_surface1_requests,
	2, gtk_surface1_events,
};

