
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__compositor_adapter_h__ADAPTOR_MARSHAL_H
#define __dbusxx__compositor_adapter_h__ADAPTOR_MARSHAL_H

#include <dbus-c++/dbus.h>
#include <cassert>

namespace org {
namespace os {

class Compositor_adaptor
: public ::DBus::InterfaceAdaptor
{
public:

    Compositor_adaptor()
    : ::DBus::InterfaceAdaptor("org.os.Compositor")
    {
        register_method(Compositor_adaptor, Views, _Views_stub);
    }

    ::DBus::IntrospectedInterface *introspect() const
    {
        static ::DBus::IntrospectedArgument Views_args[] =
        {
            { 0, "as", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedMethod Compositor_adaptor_methods[] =
        {
            { "Views", Views_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedMethod Compositor_adaptor_signals[] =
        {
            { 0, 0 }
        };
        static ::DBus::IntrospectedProperty Compositor_adaptor_properties[] =
        {
            { 0, 0, 0, 0 }
        };
        static ::DBus::IntrospectedInterface Compositor_adaptor_interface =
        {
            "org.os.Compositor",
            Compositor_adaptor_methods,
            Compositor_adaptor_signals,
            Compositor_adaptor_properties
        };
        return &Compositor_adaptor_interface;
    }

public:

    /* properties exposed by this interface, use
     * property() and property(value) to get and set a particular property
     */

public:

    /* methods exported by this interface,
     * you will have to implement them in your ObjectAdaptor
     */
    virtual std::vector< std::string > Views() = 0;

public:

    /* signal emitters for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual interface method)
     */
    ::DBus::Message _Views_stub(const ::DBus::CallMessage &call)
    {
        // ::DBus::MessageIter ri = call.reader();

        std::vector< std::string > argout1 = Views();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
};

} }
#endif //__dbusxx__compositor_adapter_h__ADAPTOR_MARSHAL_H
