
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__settings_proxy_h__PROXY_MARSHAL_H
#define __dbusxx__settings_proxy_h__PROXY_MARSHAL_H

#include <dbus-c++/dbus.h>
#include <cassert>

namespace org {
namespace os {
namespace Settings {

class Display_proxy
: public ::DBus::InterfaceProxy
{
public:

    Display_proxy()
    : ::DBus::InterfaceProxy("org.os.Settings.Display")
    {
    }

public:

    /* properties exported by this interface */
public:

    /* methods exported by this interface,
     * this functions will invoke the corresponding methods on the remote objects
     */
    std::map< std::string, ::DBus::Struct< int32_t, int32_t, int32_t, bool, bool > > FindLayout(const std::vector< ::DBus::Struct< std::string, int32_t, int32_t > >& outputs)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << outputs;
        call.member("FindLayout");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        std::map< std::string, ::DBus::Struct< int32_t, int32_t, int32_t, bool, bool > > argout;
        ri >> argout;
        return argout;
    }


public:

    /* signal handlers for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual signal handler)
     */
};

} } } 
#endif //__dbusxx__settings_proxy_h__PROXY_MARSHAL_H
